# Generated by Django 3.2.5 on 2021-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('Math', 'Math'), ('English', 'English')], default=('Chinese', 'Chinese'), max_length=20),
        ),
    ]
